name: Build Backend Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - workflow_dispatch
    paths:
      - "backend/**"
env:
  REGISTRY: docker.io
  IMAGE_NAME: mniranjanr7/booktrack-backend

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: list files
        run: |
          echo "The present working directory is:"
          pwd
          echo "The files are:"
          ls -lthr *

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Scan Python dependencies
        run: |
          pip install pip-audit
          pip-audit -r backend/requirements.txt

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Generate SBOM with SYFT
        uses: anchore/sbom-action@v0
        with:
          image: ${{env.IMAGE_NAME}}:${{ github.sha }}
          format: table
          output-file: sbom-backend-image.txt

  push-and-sign:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Docker Login Action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push image with multiplatform and registry cache
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max

      - name: Verify pushed Images
        run: docker images

      - name: Sign images with cosign (keyless)
        env:
          COSIGN_YES: true
          COSIGN_EXPERIMENTAL: "true"
        run:
          cosign sign docker.io/${{ env.IMAGE_NAME}}:${{github.sha}}
          cosign sign --keyless docker.io/${{ env.IMAGE_NAME }}:latest

          # üîç VERIFY goes HERE
      - name: Cosign verify image
        run: |
          cosign verify docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --certificate-identity-regexp github.com \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com
